# Whether to allow players to lock blocks that don't have any placer data.
allow-unplaced-locking: false


# The channel where players will send link codes to link their Minecraft and Discord accounts.
# Must be a valid channel ID, names are not supported.
link-channel: "000000000000000000"


lock-tool:
  # Whether the recipe for the Lock Tool will be enabled.
  # If false, the only way to get a Lock Tool would be through the /locktool command.
  # Only takes affect if lock-tool.custom is false.
  recipe: true
  # If the lock tool is going to use the custom Vanadium items (vanadium:lock_tool). Requires ItemsAdder
  custom: false


# Amount of time to wait before giving a new slot.
# Time unit is minutes.
slot-cooldowns:
  locks: 10
  trusts: 30


# Settings for ItemsAdder custom items
custom-items:
  # vanadium:chris_shield
  chris_shield:
    # Block ability that gives slowness
    block:
      # Slowness duration (seconds)
      duration: 5