# Whether to allow players to lock blocks that don't have any placer data.
allow-unplaced-locking: false


# The channel where players will send link codes to link their Minecraft and Discord accounts.
# Must be a valid channel ID, names are not supported.
link-channel: "000000000000000000"


# Settings for plugin data auto-save
# REQUIRES RESTART
auto-save:
  # Whether to save data automatically
  enabled: true
  # How often to save data in seconds
  interval: 600 # 10 minutes


# Settings for the lock tool
lock-tool:
  # Whether the recipe for the Lock Tool will be enabled.
  # If false, the only way to get a Lock Tool would be through the /locktool command. Unless you're using lock-tool.custom
  # Only takes affect if lock-tool.custom is false.
  recipe: true
  # If the lock tool is going to use the custom Vanadium items (vanadium:lock_tool). Requires ItemsAdder
  custom: false


# Amount of time to wait before giving a new slot.
# Time unit is minutes.
slot-cooldowns:
  locks: 30
  trusts: 40


# Settings for ItemsAdder custom items
custom-items:
  # Cooldown for all abilities
  cooldown: 3

  # vanadium:chris_shield
  chris_shield:
    # Block ability that gives attacker slowness
    block:
      # Slowness duration (seconds)
      duration: 5
    # Shift-left-click ability that damages nearby entities
    damage:
      # Amount to damage each entity
      amount: 4
      # Range entities have to be within
      range: 5

  # vanadium:chris_axe
  chris_axe:
    lightning:
      # How far the lightning can reach
      range: 30
    throw:
      # Speed of the arrow
      speed: 2
      # How much damage the arrow will do
      damage: 2
      # Time in seconds before it returns to the inventory
      return: 3

  # vanadium:nyx_wand
  nyx_wand:
    tnt:
      # How long until the TNT explodes
      fuse: 1
      # True if the TNT should explode blocks
      blocks: false

  # vanadium:vanadium_crossbow
  vanadium_crossbow:
    speed:
      # Speeed of the Ender Pearl when using an arrow
      arrow: 1.8

      # Speed of the Ender Pearl when using a Firework (per-charge)
      firework:
        1: 2.0
        2: 2.25
        3: 2.5